import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const jost = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-cover bg-no-repeat ${jost.className}`} style={{ backgroundImage: "url('assets/pngwing-1920w.webp')" }}>
        <Header />
        {children}
      </body>
    </html>
  );
}
function Jots(arg0: { subsets: string[]; }) {
  throw new Error("Function not implemented.");
}

